---
title: "First look at PTRS"
---

```{r setup}
library(dplyr)
library(data.table)
library(ggplot2)
options(stringsAsFactors = F)
parse_pop = function(x) {
  x = unlist(lapply(strsplit(x, '-'), function(y) {
    if(length(y) > 1) {
      return(paste0(y[1], '-', y[2]))
    } else {
      return(y)
    }
  }))
}
```

# Load results

```{r load}
traits = tolower(read.csv('../external_data/martin_et_al_2019ng_table_s6.csv')$Trait)
diag_df = data.frame(trait = traits, index = 1 : 17)
result = list()
for(i in 1 : 17) {
  for(t in traits) {
    filename = paste0('~/Desktop/tmp/ptrs_r2/ptrs-r2_subset', i, '_x_', t, '.txt')
    tmp = read.table(filename, header = T, sep = '\t')
    result[[length(result) + 1]] = tmp %>% mutate(subset = i, trait = t)
  }
}
df_result = do.call(rbind, result)
df_result$population = parse_pop(df_result$population)
df_result$ptrs_col = factor(df_result$ptrs_col, levels = unique(df_result$ptrs_col))
```

# Plot

```{r plot, fig.height=17, fig.width=6}
df_result %>% ggplot() + geom_boxplot(aes(x = ptrs_col, y = r2, color = population)) + facet_wrap(~trait, ncol = 1, scales = 'free_y') + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

# "Best British" model

```{r best british}
best_british = df_result %>% filter(population == 'British-validation') %>% group_by(trait, subset) %>% summarize(best_model = ptrs_col[which.max(r2)])
tmp = df_result %>% filter(paste(trait, subset, ptrs_col) %in% paste(best_british$trait, best_british$subset, best_british$best_model)) %>% group_by(trait, subset) %>% mutate(transferability = r2 / r2[population == 'British-validation'])
tmp %>% filter(paste(trait, subset) %in% paste(diag_df$trait, diag_df$index))%>% ggplot() + geom_violin(aes(x = population, y = transferability))
```

# "Best" model

```{r best model}
best_model = df_result %>% group_by(trait, subset, population) %>% summarize(best_model = ptrs_col[which.max(r2)])
tmp = df_result %>% filter(paste(trait, subset, ptrs_col, population) %in% paste(best_model$trait, best_model$subset, best_model$best_model, best_model$population)) %>% group_by(trait, subset) %>% mutate(transferability = r2 / r2[population == 'British-validation'])
tmp_clean = tmp %>% filter(paste(trait, subset) %in% paste(diag_df$trait, diag_df$index)) 
tmp_clean %>% ggplot() + geom_violin(aes(x = population, y = transferability)) + geom_jitter(aes(x = population, y = transferability), height = 0, width = 0.2)
tmp_clean$trait = factor(tmp_clean$trait, levels = tmp_clean %>% select(trait, r2) %>% summarize(r2 = median(r2)) %>% arrange(desc(r2)) %>% pull(trait))
tmp_clean %>% ggplot() + geom_point(aes(x = trait, y = r2, color = population, group = population), position = position_dodge(0.3)) + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```