#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=16gb
#PBS -e logs/ld-clump-${TRAIT}.err
#PBS -o logs/ld-clump-${TRAIT}.out

source ~/.bash_profile
source ~/.bashrc
cd /gpfs/data/im-lab/nas40t2/yanyul/GitHub/ptrs-ukb/pipeline/ld_clump

conda activate parquet

module load gcc/6.2.0
module load plink/1.90

snakemake -s ld_clump.snmk --configfile ../../submission_scripts/ld_clump/config.ld_clump.yaml --nolock threads=1 memory=16000 gwas_name=$TRAIT > ../../submission_scripts/ld_clump/logs/ld-clump-$TRAIT.log 2>&1

